import { FETCH_CAT_REQUEST, FETCH_CAT_ERROR, FETCH_CAT_SUCCESS, 
         ADOPT_CAT_REQUEST, ADOPT_CAT_ERROR, ADOPT_CAT_SUCCESS } from './cats';
import { FETCH_DOG_REQUEST, FETCH_DOG_ERROR, FETCH_DOG_SUCCESS, 
         ADOPT_DOG_REQUEST, ADOPT_DOG_ERROR, ADOPT_DOG_SUCCESS } from './dogs';


let Index = {
  FETCH_CAT_REQUEST,
  FETCH_CAT_ERROR,
  FETCH_CAT_SUCCESS, 
  ADOPT_CAT_REQUEST, 
  ADOPT_CAT_ERROR, 
  ADOPT_CAT_SUCCESS ,
  FETCH_DOG_REQUEST, 
  FETCH_DOG_ERROR, 
  FETCH_DOG_SUCCESS, 
  ADOPT_DOG_REQUEST, 
  ADOPT_DOG_ERROR, 
  ADOPT_DOG_SUCCESS
}

export default Index ;        